#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CIV.Sample.Resource", IsApplication=true)]

namespace CIV.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::de.hdodenhof.circleimageview.Resource.Attribute.civ_border_color = global::CIV.Sample.Resource.Attribute.civ_border_color;
			global::de.hdodenhof.circleimageview.Resource.Attribute.civ_border_overlay = global::CIV.Sample.Resource.Attribute.civ_border_overlay;
			global::de.hdodenhof.circleimageview.Resource.Attribute.civ_border_width = global::CIV.Sample.Resource.Attribute.civ_border_width;
			global::de.hdodenhof.circleimageview.Resource.Attribute.civ_fill_color = global::CIV.Sample.Resource.Attribute.civ_fill_color;
			global::de.hdodenhof.circleimageview.Resource.String.library_name = global::CIV.Sample.Resource.String.library_name;
			global::de.hdodenhof.circleimageview.Resource.Styleable.CircleImageView = global::CIV.Sample.Resource.Styleable.CircleImageView;
			global::de.hdodenhof.circleimageview.Resource.Styleable.CircleImageView_civ_border_color = global::CIV.Sample.Resource.Styleable.CircleImageView_civ_border_color;
			global::de.hdodenhof.circleimageview.Resource.Styleable.CircleImageView_civ_border_overlay = global::CIV.Sample.Resource.Styleable.CircleImageView_civ_border_overlay;
			global::de.hdodenhof.circleimageview.Resource.Styleable.CircleImageView_civ_border_width = global::CIV.Sample.Resource.Styleable.CircleImageView_civ_border_width;
			global::de.hdodenhof.circleimageview.Resource.Styleable.CircleImageView_civ_fill_color = global::CIV.Sample.Resource.Styleable.CircleImageView_civ_fill_color;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int civ_border_color = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int civ_border_overlay = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int civ_border_width = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int civ_fill_color = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int homer = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int profile = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int fill_image = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int large_profile_image = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int profile_image = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
