#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("de.hdodenhof.circleimageview.Resource", IsApplication=false)]

namespace de.hdodenhof.circleimageview
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int civ_border_color = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int civ_border_overlay = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int civ_border_width = 2130771968;
			
			// aapt resource value: 0x7f010003
			public static int civ_fill_color = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public static int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public static int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public static int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public static int CircleImageView_civ_fill_color = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
